//TODO: First hand research into these totals as the 3rd party advice on the number of Dark Matters required to be synthed is conflicting.
export const requiredTotalsKH = [
  { 'name': "Lucid Shard", 'qty': 35 },
  { 'name': "Lucid Gem", 'qty': 13 },
  { 'name': "Lucid Crystal", 'qty': 9 },
  { 'name': "Power Shard", 'qty': 13 },
  { 'name': "Power Gem", 'qty': 11 },
  { 'name': "Power Crystal", 'qty': 7 },
  { 'name': "Bright Shard", 'qty': 13 },
  { 'name': "Bright Gem", 'qty': 8 },
  { 'name': "Bright Crystal", 'qty': 4 },
  { 'name': "Spirit Shard", 'qty': 13 },
  { 'name': "Spirit Gem", 'qty': 7 },
  { 'name': "Shiny Crystal", 'qty': 3 },
  { 'name': "Blaze Shard", 'qty': 12 },
  { 'name': "Blaze Gem", 'qty': 10 },
  { 'name': "Frost Shard", 'qty': 10 },
  { 'name': "Frost Gem", 'qty': 10 },
  { 'name': "Thunder Shard", 'qty': 12 },
  { 'name': "Thunder Gem", 'qty': 15 },
  { 'name': "Mythril Shard", 'qty': 12 },
  { 'name': "Mythril", 'qty': 13 },
  { 'name': "Mystery Goo", 'qty': 14 },
  { 'name': "Gale", 'qty': 6 },
  { 'name': "Orichalcum", 'qty': 19 },
  { 'name': "Stormy Stone", 'qty': 4 },
  { 'name': "Fury Stone", 'qty': 5 },
  { 'name': "Power Stone", 'qty': 5 },
  { 'name': "Lightning Stone", 'qty': 5 },
  { 'name': "Energy Stone", 'qty': 6 },
  { 'name': "Dazzling Stone", 'qty': 6 },
  { 'name': "Blazing Stone", 'qty': 7 },
  { 'name': "Frost Stone", 'qty': 7 },
  { 'name': "Mythril Stone", 'qty': 8 },
  { 'name': "Serenity Power", 'qty': 7 },
  { 'name': "Dark Matter", 'qty': 14 },
]