//TODO: First hand research into these totals as the 3rd party advice on the number of Dark Matters required to be synthed is conflicting.
export const requiredTotalsKH = [
    {'name':"Lucid Shard",'total':35},
    {'name':"Lucid Gem",'total':13},
    {'name':"Lucid Crystal",'total':9},
    {'name':"Power Shard",'total':13},
    {'name':"Power Gem",'total':11},
    {'name':"Power Crystal",'total':7},
    {'name':"Bright Shard",'total':13},
    {'name':"Bright Gem",'total':8},
    {'name':"Bright Crystal",'total':4},
    {'name':"Spirit Shard",'total':13},
    {'name':"Spirit Gem",'total': 7},
    {'name':"Shiny Crystal",'total':3},
    {'name':"Blaze Shard",'total':12},
    {'name':"Blaze Gem",'total':10},
    {'name':"Frost Shard",'total':10},
    {'name':"Frost Gem",'total':10},
    {'name':"Thunder Shard",'total':12},
    {'name':"Thunder Gem",'total':15},
    {'name':"Mythril Shard",'total':12},
    {'name':"Mythril",'total':13},
    {'name':"Mystery Goo",'total':14},
    {'name':"Gale",'total':6},
    {'name':"Orichalcum",'total':19},
    {'name':"Stormy Stone",'total':4},
    {'name':"Fury Stone",'total':5},
    {'name':"Power Stone",'total':5},
    {'name':"Lightning Stone",'total':5},
    {'name':"Energy Stone",'total':6},
    {'name':"Dazzling Stone",'total':6},
    {'name':"Blazing Stone",'total':7},
    {'name':"Frost Stone",'total':7},
    {'name':"Mythril Stone",'total':8},
    {'name':"Serenity Power",'total':7},
    {'name':"Dark Matter",'total':14},
]